# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.super_routes_reply_api import SuperRoutesReplyApi


class TestSuperRoutesReplyApi(unittest.TestCase):
    """SuperRoutesReplyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperRoutesReplyApi()

    def tearDown(self) -> None:
        pass

    def test_confirm_permission(self) -> None:
        """Test case for confirm_permission

        """
        pass


if __name__ == '__main__':
    unittest.main()
