# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.recipe_management_api import RecipeManagementApi


class TestRecipeManagementApi(unittest.TestCase):
    """RecipeManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecipeManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_recipe(self) -> None:
        """Test case for create_recipe

        Create a Recipe configuration from the current session
        """
        pass

    def test_decode_recipe(self) -> None:
        """Test case for decode_recipe

        """
        pass

    def test_delete_recipe(self) -> None:
        """Test case for delete_recipe

        """
        pass

    def test_encode_recipe(self) -> None:
        """Test case for encode_recipe

        """
        pass

    def test_list_recipes(self) -> None:
        """Test case for list_recipes

        """
        pass

    def test_scan_recipe(self) -> None:
        """Test case for scan_recipe

        """
        pass


if __name__ == '__main__':
    unittest.main()
