# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.extend_prompt_request import ExtendPromptRequest

class TestExtendPromptRequest(unittest.TestCase):
    """ExtendPromptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtendPromptRequest:
        """Test ExtendPromptRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtendPromptRequest`
        """
        model = ExtendPromptRequest()
        if include_optional:
            return ExtendPromptRequest(
                extension = '',
                session_id = ''
            )
        else:
            return ExtendPromptRequest(
                extension = '',
                session_id = '',
        )
        """

    def testExtendPromptRequest(self):
        """Test ExtendPromptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
