# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.raw_resource import RawResource

class TestRawResource(unittest.TestCase):
    """RawResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RawResource:
        """Test RawResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RawResource`
        """
        model = RawResource()
        if include_optional:
            return RawResource(
                description = '',
                icons = [
                    goose_api.models.icon.Icon(
                        mime_type = '', 
                        sizes = '', 
                        src = '', )
                    ],
                mime_type = '',
                name = '',
                size = 0,
                title = '',
                uri = ''
            )
        else:
            return RawResource(
                name = '',
                uri = '',
        )
        """

    def testRawResource(self):
        """Test RawResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
