# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.principal_type import PrincipalType

class TestPrincipalType(unittest.TestCase):
    """PrincipalType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrincipalType(self):
        """Test PrincipalType"""
        # inst = PrincipalType()

if __name__ == '__main__':
    unittest.main()
