# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.message_content_one_of8 import MessageContentOneOf8

class TestMessageContentOneOf8(unittest.TestCase):
    """MessageContentOneOf8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageContentOneOf8:
        """Test MessageContentOneOf8
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageContentOneOf8`
        """
        model = MessageContentOneOf8()
        if include_optional:
            return MessageContentOneOf8(
                msg = '',
                type = 'contextLengthExceeded'
            )
        else:
            return MessageContentOneOf8(
                msg = '',
                type = 'contextLengthExceeded',
        )
        """

    def testMessageContentOneOf8(self):
        """Test MessageContentOneOf8"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
