# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.message_content_one_of6 import MessageContentOneOf6

class TestMessageContentOneOf6(unittest.TestCase):
    """MessageContentOneOf6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageContentOneOf6:
        """Test MessageContentOneOf6
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageContentOneOf6`
        """
        model = MessageContentOneOf6()
        if include_optional:
            return MessageContentOneOf6(
                signature = '',
                thinking = '',
                type = 'thinking'
            )
        else:
            return MessageContentOneOf6(
                signature = '',
                thinking = '',
                type = 'thinking',
        )
        """

    def testMessageContentOneOf6(self):
        """Test MessageContentOneOf6"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
