# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.resource_contents_any_of1 import ResourceContentsAnyOf1

class TestResourceContentsAnyOf1(unittest.TestCase):
    """ResourceContentsAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceContentsAnyOf1:
        """Test ResourceContentsAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceContentsAnyOf1`
        """
        model = ResourceContentsAnyOf1()
        if include_optional:
            return ResourceContentsAnyOf1(
                meta = { },
                blob = '',
                mime_type = '',
                uri = ''
            )
        else:
            return ResourceContentsAnyOf1(
                blob = '',
                uri = '',
        )
        """

    def testResourceContentsAnyOf1(self):
        """Test ResourceContentsAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
