# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.super_routes_config_management_api import SuperRoutesConfigManagementApi


class TestSuperRoutesConfigManagementApi(unittest.TestCase):
    """SuperRoutesConfigManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperRoutesConfigManagementApi()

    def tearDown(self) -> None:
        pass

    def test_add_extension(self) -> None:
        """Test case for add_extension

        """
        pass

    def test_backup_config(self) -> None:
        """Test case for backup_config

        """
        pass

    def test_create_custom_provider(self) -> None:
        """Test case for create_custom_provider

        """
        pass

    def test_get_extensions(self) -> None:
        """Test case for get_extensions

        """
        pass

    def test_get_provider_models(self) -> None:
        """Test case for get_provider_models

        """
        pass

    def test_init_config(self) -> None:
        """Test case for init_config

        """
        pass

    def test_providers(self) -> None:
        """Test case for providers

        """
        pass

    def test_read_all_config(self) -> None:
        """Test case for read_all_config

        """
        pass

    def test_read_config(self) -> None:
        """Test case for read_config

        """
        pass

    def test_recover_config(self) -> None:
        """Test case for recover_config

        """
        pass

    def test_remove_config(self) -> None:
        """Test case for remove_config

        """
        pass

    def test_remove_custom_provider(self) -> None:
        """Test case for remove_custom_provider

        """
        pass

    def test_remove_extension(self) -> None:
        """Test case for remove_extension

        """
        pass

    def test_upsert_config(self) -> None:
        """Test case for upsert_config

        """
        pass

    def test_upsert_permissions(self) -> None:
        """Test case for upsert_permissions

        """
        pass

    def test_validate_config(self) -> None:
        """Test case for validate_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
