# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.session_list_response import SessionListResponse

class TestSessionListResponse(unittest.TestCase):
    """SessionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionListResponse:
        """Test SessionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionListResponse`
        """
        model = SessionListResponse()
        if include_optional:
            return SessionListResponse(
                sessions = [
                    goose_api.models.session.Session(
                        accumulated_input_tokens = 56, 
                        accumulated_output_tokens = 56, 
                        accumulated_total_tokens = 56, 
                        conversation = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        extension_data = {
                            'key' : null
                            }, 
                        id = '', 
                        input_tokens = 56, 
                        message_count = 0, 
                        output_tokens = 56, 
                        recipe = null, 
                        schedule_id = '', 
                        total_tokens = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        working_dir = '', )
                    ]
            )
        else:
            return SessionListResponse(
                sessions = [
                    goose_api.models.session.Session(
                        accumulated_input_tokens = 56, 
                        accumulated_output_tokens = 56, 
                        accumulated_total_tokens = 56, 
                        conversation = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        extension_data = {
                            'key' : null
                            }, 
                        id = '', 
                        input_tokens = 56, 
                        message_count = 0, 
                        output_tokens = 56, 
                        recipe = null, 
                        schedule_id = '', 
                        total_tokens = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        working_dir = '', )
                    ],
        )
        """

    def testSessionListResponse(self):
        """Test SessionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
