# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.decode_recipe_request import DecodeRecipeRequest

class TestDecodeRecipeRequest(unittest.TestCase):
    """DecodeRecipeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecodeRecipeRequest:
        """Test DecodeRecipeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecodeRecipeRequest`
        """
        model = DecodeRecipeRequest()
        if include_optional:
            return DecodeRecipeRequest(
                deeplink = ''
            )
        else:
            return DecodeRecipeRequest(
                deeplink = '',
        )
        """

    def testDecodeRecipeRequest(self):
        """Test DecodeRecipeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
