# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.image_content import ImageContent

class TestImageContent(unittest.TestCase):
    """ImageContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageContent:
        """Test ImageContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageContent`
        """
        model = ImageContent()
        if include_optional:
            return ImageContent(
                meta = { },
                annotations = None,
                data = '',
                mime_type = ''
            )
        else:
            return ImageContent(
                data = '',
                mime_type = '',
        )
        """

    def testImageContent(self):
        """Test ImageContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
