# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.recipe_parameter_input_type import RecipeParameterInputType

class TestRecipeParameterInputType(unittest.TestCase):
    """RecipeParameterInputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecipeParameterInputType(self):
        """Test RecipeParameterInputType"""
        # inst = RecipeParameterInputType()

if __name__ == '__main__':
    unittest.main()
