# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.session_display_info import SessionDisplayInfo

class TestSessionDisplayInfo(unittest.TestCase):
    """SessionDisplayInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionDisplayInfo:
        """Test SessionDisplayInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionDisplayInfo`
        """
        model = SessionDisplayInfo()
        if include_optional:
            return SessionDisplayInfo(
                accumulated_input_tokens = 56,
                accumulated_output_tokens = 56,
                accumulated_total_tokens = 56,
                created_at = '',
                id = '',
                input_tokens = 56,
                message_count = 0,
                name = '',
                output_tokens = 56,
                schedule_id = '',
                total_tokens = 56,
                working_dir = ''
            )
        else:
            return SessionDisplayInfo(
                created_at = '',
                id = '',
                message_count = 0,
                name = '',
                working_dir = '',
        )
        """

    def testSessionDisplayInfo(self):
        """Test SessionDisplayInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
