# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.create_custom_provider_request import CreateCustomProviderRequest

class TestCreateCustomProviderRequest(unittest.TestCase):
    """CreateCustomProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCustomProviderRequest:
        """Test CreateCustomProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCustomProviderRequest`
        """
        model = CreateCustomProviderRequest()
        if include_optional:
            return CreateCustomProviderRequest(
                api_key = '',
                api_url = '',
                display_name = '',
                models = [
                    ''
                    ],
                provider_type = '',
                supports_streaming = True
            )
        else:
            return CreateCustomProviderRequest(
                api_key = '',
                api_url = '',
                display_name = '',
                models = [
                    ''
                    ],
                provider_type = '',
        )
        """

    def testCreateCustomProviderRequest(self):
        """Test CreateCustomProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
