# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.tool_response import ToolResponse

class TestToolResponse(unittest.TestCase):
    """ToolResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolResponse:
        """Test ToolResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolResponse`
        """
        model = ToolResponse()
        if include_optional:
            return ToolResponse(
                id = '',
                tool_result = None
            )
        else:
            return ToolResponse(
                id = '',
                tool_result = None,
        )
        """

    def testToolResponse(self):
        """Test ToolResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
