# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.extension_config import ExtensionConfig

class TestExtensionConfig(unittest.TestCase):
    """ExtensionConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtensionConfig:
        """Test ExtensionConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtensionConfig`
        """
        model = ExtensionConfig()
        if include_optional:
            return ExtensionConfig(
                available_tools = [
                    ''
                    ],
                bundled = True,
                description = '',
                env_keys = [
                    ''
                    ],
                envs = {
                    'key' : ''
                    },
                name = '',
                timeout = 0,
                type = 'sse',
                uri = '',
                args = [
                    ''
                    ],
                cmd = '',
                display_name = '',
                headers = {
                    'key' : ''
                    },
                instructions = '',
                tools = [
                    goose_api.models.tool.Tool(
                        annotations = null, 
                        description = '', 
                        icons = [
                            goose_api.models.icon.Icon(
                                mime_type = '', 
                                sizes = '', 
                                src = '', )
                            ], 
                        input_schema = { }, 
                        name = '', 
                        output_schema = { }, 
                        title = '', )
                    ],
                code = '',
                dependencies = [
                    ''
                    ]
            )
        else:
            return ExtensionConfig(
                name = '',
                type = 'sse',
                uri = '',
                args = [
                    ''
                    ],
                cmd = '',
                tools = [
                    goose_api.models.tool.Tool(
                        annotations = null, 
                        description = '', 
                        icons = [
                            goose_api.models.icon.Icon(
                                mime_type = '', 
                                sizes = '', 
                                src = '', )
                            ], 
                        input_schema = { }, 
                        name = '', 
                        output_schema = { }, 
                        title = '', )
                    ],
                code = '',
        )
        """

    def testExtensionConfig(self):
        """Test ExtensionConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
