# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.update_provider_request import UpdateProviderRequest

class TestUpdateProviderRequest(unittest.TestCase):
    """UpdateProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProviderRequest:
        """Test UpdateProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProviderRequest`
        """
        model = UpdateProviderRequest()
        if include_optional:
            return UpdateProviderRequest(
                model = '',
                provider = '',
                session_id = ''
            )
        else:
            return UpdateProviderRequest(
                provider = '',
                session_id = '',
        )
        """

    def testUpdateProviderRequest(self):
        """Test UpdateProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
