# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.tool_annotations import ToolAnnotations

class TestToolAnnotations(unittest.TestCase):
    """ToolAnnotations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolAnnotations:
        """Test ToolAnnotations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolAnnotations`
        """
        model = ToolAnnotations()
        if include_optional:
            return ToolAnnotations(
                destructive_hint = True,
                idempotent_hint = True,
                open_world_hint = True,
                read_only_hint = True,
                title = ''
            )
        else:
            return ToolAnnotations(
        )
        """

    def testToolAnnotations(self):
        """Test ToolAnnotations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
