# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.super_routes_health_api import SuperRoutesHealthApi


class TestSuperRoutesHealthApi(unittest.TestCase):
    """SuperRoutesHealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperRoutesHealthApi()

    def tearDown(self) -> None:
        pass

    def test_status(self) -> None:
        """Test case for status

        """
        pass


if __name__ == '__main__':
    unittest.main()
