# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.session_management_api import SessionManagementApi


class TestSessionManagementApi(unittest.TestCase):
    """SessionManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionManagementApi()

    def tearDown(self) -> None:
        pass

    def test_delete_session(self) -> None:
        """Test case for delete_session

        """
        pass

    def test_get_session(self) -> None:
        """Test case for get_session

        """
        pass

    def test_get_session_insights(self) -> None:
        """Test case for get_session_insights

        """
        pass

    def test_list_sessions(self) -> None:
        """Test case for list_sessions

        """
        pass

    def test_update_session_description(self) -> None:
        """Test case for update_session_description

        """
        pass


if __name__ == '__main__':
    unittest.main()
