# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.recipe_parameter import RecipeParameter

class TestRecipeParameter(unittest.TestCase):
    """RecipeParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipeParameter:
        """Test RecipeParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipeParameter`
        """
        model = RecipeParameter()
        if include_optional:
            return RecipeParameter(
                default = '',
                description = '',
                input_type = 'string',
                key = '',
                options = [
                    ''
                    ],
                requirement = 'required'
            )
        else:
            return RecipeParameter(
                description = '',
                input_type = 'string',
                key = '',
                requirement = 'required',
        )
        """

    def testRecipeParameter(self):
        """Test RecipeParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
