# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.extension_config_one_of2 import ExtensionConfigOneOf2

class TestExtensionConfigOneOf2(unittest.TestCase):
    """ExtensionConfigOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtensionConfigOneOf2:
        """Test ExtensionConfigOneOf2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtensionConfigOneOf2`
        """
        model = ExtensionConfigOneOf2()
        if include_optional:
            return ExtensionConfigOneOf2(
                available_tools = [
                    ''
                    ],
                bundled = True,
                description = '',
                display_name = '',
                name = '',
                timeout = 0,
                type = 'builtin'
            )
        else:
            return ExtensionConfigOneOf2(
                name = '',
                type = 'builtin',
        )
        """

    def testExtensionConfigOneOf2(self):
        """Test ExtensionConfigOneOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
