# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.super_routes_agent_api import SuperRoutesAgentApi


class TestSuperRoutesAgentApi(unittest.TestCase):
    """SuperRoutesAgentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperRoutesAgentApi()

    def tearDown(self) -> None:
        pass

    def test_add_sub_recipes(self) -> None:
        """Test case for add_sub_recipes

        """
        pass

    def test_extend_prompt(self) -> None:
        """Test case for extend_prompt

        """
        pass

    def test_get_tools(self) -> None:
        """Test case for get_tools

        """
        pass

    def test_resume_agent(self) -> None:
        """Test case for resume_agent

        """
        pass

    def test_start_agent(self) -> None:
        """Test case for start_agent

        """
        pass

    def test_update_agent_provider(self) -> None:
        """Test case for update_agent_provider

        """
        pass

    def test_update_router_tool_selector(self) -> None:
        """Test case for update_router_tool_selector

        """
        pass

    def test_update_session_config(self) -> None:
        """Test case for update_session_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
