# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.create_schedule_request import CreateScheduleRequest

class TestCreateScheduleRequest(unittest.TestCase):
    """CreateScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateScheduleRequest:
        """Test CreateScheduleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateScheduleRequest`
        """
        model = CreateScheduleRequest()
        if include_optional:
            return CreateScheduleRequest(
                cron = '',
                execution_mode = '',
                id = '',
                recipe_source = ''
            )
        else:
            return CreateScheduleRequest(
                cron = '',
                id = '',
                recipe_source = '',
        )
        """

    def testCreateScheduleRequest(self):
        """Test CreateScheduleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
