# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.permission_level import PermissionLevel

class TestPermissionLevel(unittest.TestCase):
    """PermissionLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPermissionLevel(self):
        """Test PermissionLevel"""
        # inst = PermissionLevel()

if __name__ == '__main__':
    unittest.main()
