# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.schedule_api import ScheduleApi


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduleApi()

    def tearDown(self) -> None:
        pass

    def test_create_schedule(self) -> None:
        """Test case for create_schedule

        """
        pass

    def test_delete_schedule(self) -> None:
        """Test case for delete_schedule

        """
        pass

    def test_inspect_running_job(self) -> None:
        """Test case for inspect_running_job

        """
        pass

    def test_kill_running_job(self) -> None:
        """Test case for kill_running_job

        """
        pass

    def test_list_schedules(self) -> None:
        """Test case for list_schedules

        """
        pass

    def test_pause_schedule(self) -> None:
        """Test case for pause_schedule

        """
        pass

    def test_run_now_handler(self) -> None:
        """Test case for run_now_handler

        """
        pass

    def test_sessions_handler(self) -> None:
        """Test case for sessions_handler

        """
        pass

    def test_unpause_schedule(self) -> None:
        """Test case for unpause_schedule

        """
        pass

    def test_update_schedule(self) -> None:
        """Test case for update_schedule

        """
        pass


if __name__ == '__main__':
    unittest.main()
