# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.models.extension_config_one_of5 import ExtensionConfigOneOf5

class TestExtensionConfigOneOf5(unittest.TestCase):
    """ExtensionConfigOneOf5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtensionConfigOneOf5:
        """Test ExtensionConfigOneOf5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtensionConfigOneOf5`
        """
        model = ExtensionConfigOneOf5()
        if include_optional:
            return ExtensionConfigOneOf5(
                available_tools = [
                    ''
                    ],
                code = '',
                dependencies = [
                    ''
                    ],
                description = '',
                name = '',
                timeout = 0,
                type = 'inline_python'
            )
        else:
            return ExtensionConfigOneOf5(
                code = '',
                name = '',
                type = 'inline_python',
        )
        """

    def testExtensionConfigOneOf5(self):
        """Test ExtensionConfigOneOf5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
