# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goose_api.api.super_routes_setup_api import SuperRoutesSetupApi


class TestSuperRoutesSetupApi(unittest.TestCase):
    """SuperRoutesSetupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SuperRoutesSetupApi()

    def tearDown(self) -> None:
        pass

    def test_start_openrouter_setup(self) -> None:
        """Test case for start_openrouter_setup

        """
        pass

    def test_start_tetrate_setup(self) -> None:
        """Test case for start_tetrate_setup

        """
        pass


if __name__ == '__main__':
    unittest.main()
