# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InspectJobResponse(BaseModel):
    """
    InspectJobResponse
    """ # noqa: E501
    process_start_time: Optional[StrictStr] = Field(default=None, alias="processStartTime")
    running_duration_seconds: Optional[StrictInt] = Field(default=None, alias="runningDurationSeconds")
    session_id: Optional[StrictStr] = Field(default=None, alias="sessionId")
    __properties: ClassVar[List[str]] = ["processStartTime", "runningDurationSeconds", "sessionId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InspectJobResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if process_start_time (nullable) is None
        # and model_fields_set contains the field
        if self.process_start_time is None and "process_start_time" in self.model_fields_set:
            _dict['processStartTime'] = None

        # set to None if running_duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.running_duration_seconds is None and "running_duration_seconds" in self.model_fields_set:
            _dict['runningDurationSeconds'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['sessionId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InspectJobResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "processStartTime": obj.get("processStartTime"),
            "runningDurationSeconds": obj.get("runningDurationSeconds"),
            "sessionId": obj.get("sessionId")
        })
        return _obj


