# coding: utf-8

"""
    goose-server

    An AI agent

    The version of the OpenAPI document: 1.9.0
    Contact: ai-oss-tools@block.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RecipeParameterInputType(str, Enum):
    """
    RecipeParameterInputType
    """

    """
    allowed enum values
    """
    STRING = 'string'
    NUMBER = 'number'
    BOOLEAN = 'boolean'
    DATE = 'date'
    FILE = 'file'
    SELECT = 'select'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RecipeParameterInputType from a JSON string"""
        return cls(json.loads(json_str))


