//
// Author.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Author: Codable, JSONEncodable, Hashable {

    public var contact: String?
    public var metadata: String?

    public init(contact: String? = nil, metadata: String? = nil) {
        self.contact = contact
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contact
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contact, forKey: .contact)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

