//
// ConfigKeyQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConfigKeyQuery: Codable, JSONEncodable, Hashable {

    public var isSecret: Bool
    public var key: String

    public init(isSecret: Bool, key: String) {
        self.isSecret = isSecret
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSecret = "is_secret"
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSecret, forKey: .isSecret)
        try container.encode(key, forKey: .key)
    }
}

