//
// ContextManageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response from context management operations */
public struct ContextManageResponse: Codable, JSONEncodable, Hashable {

    /** Processed messages after the operation */
    public var messages: [Message]
    /** Token counts for each processed message */
    public var tokenCounts: [Int]

    public init(messages: [Message], tokenCounts: [Int]) {
        self.messages = messages
        self.tokenCounts = tokenCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
        case tokenCounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messages, forKey: .messages)
        try container.encode(tokenCounts, forKey: .tokenCounts)
    }
}

