//
// ContextManageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request payload for context management operations */
public struct ContextManageRequest: Codable, JSONEncodable, Hashable {

    /** Operation to perform: \"truncation\" or \"summarize\" */
    public var manageAction: String
    /** Collection of messages to be managed */
    public var messages: [Message]
    /** Optional session ID for session-specific agent */
    public var sessionId: String

    public init(manageAction: String, messages: [Message], sessionId: String) {
        self.manageAction = manageAction
        self.messages = messages
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case manageAction
        case messages
        case sessionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(manageAction, forKey: .manageAction)
        try container.encode(messages, forKey: .messages)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

