//
// CreateScheduleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateScheduleRequest: Codable, JSONEncodable, Hashable {

    public var cron: String
    public var executionMode: String?
    public var id: String
    public var recipeSource: String

    public init(cron: String, executionMode: String? = nil, id: String, recipeSource: String) {
        self.cron = cron
        self.executionMode = executionMode
        self.id = id
        self.recipeSource = recipeSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cron
        case executionMode = "execution_mode"
        case id
        case recipeSource = "recipe_source"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cron, forKey: .cron)
        try container.encodeIfPresent(executionMode, forKey: .executionMode)
        try container.encode(id, forKey: .id)
        try container.encode(recipeSource, forKey: .recipeSource)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateScheduleRequest: Identifiable {}
