//
// EmbeddedResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmbeddedResource: Codable, JSONEncodable, Hashable {

    public var meta: [String: AnyCodable]?
    public var annotations: EmbeddedResourceAnnotations?
    public var resource: ResourceContents

    public init(meta: [String: AnyCodable]? = nil, annotations: EmbeddedResourceAnnotations? = nil, resource: ResourceContents) {
        self.meta = meta
        self.annotations = annotations
        self.resource = resource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta = "_meta"
        case annotations
        case resource
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(annotations, forKey: .annotations)
        try container.encode(resource, forKey: .resource)
    }
}

