//
// EmbeddedResourceAnnotations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmbeddedResourceAnnotations: Codable, JSONEncodable, Hashable {

    public var audience: [String]?
    public var lastModified: Date?
    public var priority: Double?

    public init(audience: [String]? = nil, lastModified: Date? = nil, priority: Double? = nil) {
        self.audience = audience
        self.lastModified = lastModified
        self.priority = priority
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audience
        case lastModified
        case priority
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(audience, forKey: .audience)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(priority, forKey: .priority)
    }
}

