//
// GetToolsQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetToolsQuery: Codable, JSONEncodable, Hashable {

    public var extensionName: String?
    public var sessionId: String

    public init(extensionName: String? = nil, sessionId: String) {
        self.extensionName = extensionName
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extensionName = "extension_name"
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(extensionName, forKey: .extensionName)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

