//
// InspectJobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InspectJobResponse: Codable, JSONEncodable, Hashable {

    public var processStartTime: String?
    public var runningDurationSeconds: Int64?
    public var sessionId: String?

    public init(processStartTime: String? = nil, runningDurationSeconds: Int64? = nil, sessionId: String? = nil) {
        self.processStartTime = processStartTime
        self.runningDurationSeconds = runningDurationSeconds
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case processStartTime
        case runningDurationSeconds
        case sessionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(processStartTime, forKey: .processStartTime)
        try container.encodeIfPresent(runningDurationSeconds, forKey: .runningDurationSeconds)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
    }
}

