//
// ListRecipeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListRecipeResponse: Codable, JSONEncodable, Hashable {

    public var recipeManifestResponses: [RecipeManifestResponse]

    public init(recipeManifestResponses: [RecipeManifestResponse]) {
        self.recipeManifestResponses = recipeManifestResponses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipeManifestResponses = "recipe_manifest_responses"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipeManifestResponses, forKey: .recipeManifestResponses)
    }
}

