//
// MessageContentOneOf6.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessageContentOneOf6: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case thinking = "thinking"
    }
    public var signature: String
    public var thinking: String
    public var type: ModelType

    public init(signature: String, thinking: String, type: ModelType) {
        self.signature = signature
        self.thinking = thinking
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signature
        case thinking
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signature, forKey: .signature)
        try container.encode(thinking, forKey: .thinking)
        try container.encode(type, forKey: .type)
    }
}

