//
// MessageContentOneOf8.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessageContentOneOf8: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case contextlengthexceeded = "contextLengthExceeded"
    }
    public var msg: String
    public var type: ModelType

    public init(msg: String, type: ModelType) {
        self.msg = msg
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case msg
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(msg, forKey: .msg)
        try container.encode(type, forKey: .type)
    }
}

