//
// ModelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelResponse: Codable, JSONEncodable, Hashable {

    public var jsonSchema: AnyCodable?

    public init(jsonSchema: AnyCodable? = nil) {
        self.jsonSchema = jsonSchema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jsonSchema = "json_schema"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jsonSchema, forKey: .jsonSchema)
    }
}

