//
// PermissionLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Enum representing the possible permission levels for a tool. */
public enum PermissionLevel: String, Codable, CaseIterable {
    case alwaysAllow = "always_allow"
    case askBefore = "ask_before"
    case neverAllow = "never_allow"
}
