//
// PermissionConfirmationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PermissionConfirmationRequest: Codable, JSONEncodable, Hashable {

    public var action: String
    public var id: String
    public var principalType: PrincipalType?
    public var sessionId: String

    public init(action: String, id: String, principalType: PrincipalType? = nil, sessionId: String) {
        self.action = action
        self.id = id
        self.principalType = principalType
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case id
        case principalType = "principal_type"
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(principalType, forKey: .principalType)
        try container.encode(sessionId, forKey: .sessionId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PermissionConfirmationRequest: Identifiable {}
