//
// PrincipalType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PrincipalType: String, Codable, CaseIterable {
    case _extension = "Extension"
    case tool = "Tool"
}
