//
// ProviderDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProviderDetails: Codable, JSONEncodable, Hashable {

    public var isConfigured: Bool
    public var metadata: ProviderMetadata
    public var name: String

    public init(isConfigured: Bool, metadata: ProviderMetadata, name: String) {
        self.isConfigured = isConfigured
        self.metadata = metadata
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isConfigured = "is_configured"
        case metadata
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isConfigured, forKey: .isConfigured)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(name, forKey: .name)
    }
}

