//
// ResourceContentsAnyOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResourceContentsAnyOf1: Codable, JSONEncodable, Hashable {

    public var meta: [String: AnyCodable]?
    public var blob: String
    public var mimeType: String?
    public var uri: String

    public init(meta: [String: AnyCodable]? = nil, blob: String, mimeType: String? = nil, uri: String) {
        self.meta = meta
        self.blob = blob
        self.mimeType = mimeType
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta = "_meta"
        case blob
        case mimeType
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encode(blob, forKey: .blob)
        try container.encodeIfPresent(mimeType, forKey: .mimeType)
        try container.encode(uri, forKey: .uri)
    }
}

