//
// ScanRecipeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScanRecipeResponse: Codable, JSONEncodable, Hashable {

    public var hasSecurityWarnings: Bool

    public init(hasSecurityWarnings: Bool) {
        self.hasSecurityWarnings = hasSecurityWarnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasSecurityWarnings = "has_security_warnings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hasSecurityWarnings, forKey: .hasSecurityWarnings)
    }
}

