//
// SessionConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionConfigRequest: Codable, JSONEncodable, Hashable {

    public var response: ModelResponse?
    public var sessionId: String

    public init(response: ModelResponse? = nil, sessionId: String) {
        self.response = response
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case response
        case sessionId = "session_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(response, forKey: .response)
        try container.encode(sessionId, forKey: .sessionId)
    }
}

