//
// SessionListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionListResponse: Codable, JSONEncodable, Hashable {

    /** List of available session information objects */
    public var sessions: [Session]

    public init(sessions: [Session]) {
        self.sessions = sessions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessions, forKey: .sessions)
    }
}

