//
// ThinkingContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ThinkingContent: Codable, JSONEncodable, Hashable {

    public var signature: String
    public var thinking: String

    public init(signature: String, thinking: String) {
        self.signature = signature
        self.thinking = thinking
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signature
        case thinking
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signature, forKey: .signature)
        try container.encode(thinking, forKey: .thinking)
    }
}

