//
// ToolResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToolResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var toolResult: AnyCodable

    public init(id: String, toolResult: AnyCodable) {
        self.id = id
        self.toolResult = toolResult
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case toolResult
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(toolResult, forKey: .toolResult)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ToolResponse: Identifiable {}
