//
// ToolPermission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToolPermission: Codable, JSONEncodable, Hashable {

    public var permission: PermissionLevel
    public var toolName: String

    public init(permission: PermissionLevel, toolName: String) {
        self.permission = permission
        self.toolName = toolName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permission
        case toolName = "tool_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(permission, forKey: .permission)
        try container.encode(toolName, forKey: .toolName)
    }
}

