//
// ToolRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToolRequest: Codable, JSONEncodable, Hashable {

    public var id: String
    public var toolCall: AnyCodable

    public init(id: String, toolCall: AnyCodable) {
        self.id = id
        self.toolCall = toolCall
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case toolCall
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(toolCall, forKey: .toolCall)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ToolRequest: Identifiable {}
