//
// ToolInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about the tool used for building prompts */
public struct ToolInfo: Codable, JSONEncodable, Hashable {

    public var description: String
    public var name: String
    public var parameters: [String]
    public var permission: PermissionLevel?

    public init(description: String, name: String, parameters: [String], permission: PermissionLevel? = nil) {
        self.description = description
        self.name = name
        self.parameters = parameters
        self.permission = permission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case name
        case parameters
        case permission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encode(parameters, forKey: .parameters)
        try container.encodeIfPresent(permission, forKey: .permission)
    }
}

