//
// UpdateScheduleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateScheduleRequest: Codable, JSONEncodable, Hashable {

    public var cron: String

    public init(cron: String) {
        self.cron = cron
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cron
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cron, forKey: .cron)
    }
}

