//
// UpsertConfigQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpsertConfigQuery: Codable, JSONEncodable, Hashable {

    public var isSecret: Bool
    public var key: String
    public var value: AnyCodable?

    public init(isSecret: Bool, key: String, value: AnyCodable?) {
        self.isSecret = isSecret
        self.key = key
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSecret = "is_secret"
        case key
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSecret, forKey: .isSecret)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
    }
}

